final int SCREENX = 500;
final int SCREENY = 500;
final int MARGIN = 50;
final int PADDLEHEIGHT = 20;
final int PADDLEWIDTH = 90;
final int LIVES = 3;
int maxSpeed = 10;
float speedLevelx = 1;
float speedLevely = 1;
int collidedWith = 0;
int myFrames = 0;boolean reset = false;
